guzzle:
    # (de)activate logging/profiler; default: %kernel.debug%
    logging: true

    clients:
        guzzle.parse.start_point:
            base_url: "https://prozorro.gov.ua/tender/search/?status=active.auction"

